[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
vopay = "2BqHZjo6i4qGLeqU43KFHeW7qwymY9PXc5J5iXzsrsKK"

[programs.localnet]
vopay = "2BqHZjo6i4qGLeqU43KFHeW7qwymY9PXc5J5iXzsrsKK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/v1ktor/.config/solana/id.json"

[scripts]
test = "npm run anchor:test"
